export type {
  StoreHero,
  Store,
  HeroLabels,
  HeroViewModel,
  SectionData,
  StaffSectionMeta,
  SuggestionsSectionMeta,
  StorePageData,
  Suggestion,
  MenuItem,
  Service,
  StaffMember,
  Product,
  Review,
  SectionMeta,
  SidebarMeta,
  SliderBreakpoints,
} from "@/types/store";
